all:	CLIENT LIBGEN CMD DEFAULTS

CLIENT:
	cd client; make

LIBGEN:
	cd libgen; make

CMD:
	cd cmd; make

DEFAULTS:
	cd defaults; make


clean:
	cd client; make clean
	cd libgen; make clean
	cd cmd; make clean
	cd defaults; make clean
	rm -f ,*
