/*
** Generated by X-Designer
*/

/*
** X-Designer-generated prelude.
** Do not edit lines before "End of X-Designer generated prelude"
** Lines beginning ** X-Designer Stub indicate a stub
** which will not be output on re-generation
*/

/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/TextF.h>

#include "textf_base.h"



/* End of X-Designer generated prelude */
/*
** X-Designer Stub popup_handler_callback
*/

#ifndef   _NO_PROTO
void popup_handler_callback(Widget w, XtPointer client_data, XtPointer xt_call_data)
#else  /* _NO_PROTO */
void popup_handler_callback(w, client_data, call_data)
	Widget    w ;
	XtPointer client_data ;
	XmPopupHandlerCallbackStruct * call_data ;
#endif /* _NO_PROTO */
{
#ifndef   _NO_PROTO
	XmPopupHandlerCallbackStruct *call_data = (XmPopupHandlerCallbackStruct *) xt_call_data ;
#endif /* _NO_PROTO */
	XEvent *event = call_data->event ;

	/*
	** If there is a primary selection, popup the cut/copy/paste menu.
	** Otherwise, popup the read/write menu.
	*/

	if (event->type != ButtonPress) {
		call_data->postIt = False ;
	}
	else if (call_data->reason == XmCR_POST) {
		char  *selection = XmTextFieldGetSelection(w) ;
		Widget menu      = (Widget) 0 ;

		if (selection != (char *) 0) {
			if (textf_popupA == (textf_popupA_p) 0)
				textf_popupA = create_textf_popupA(XtParent(w)) ;
			
			menu = textf_popupA->textf_popupA ;
		}
		else {
			if (textf_popupB == (textf_popupB_p) 0)
				textf_popupB = create_textf_popupB(XtParent(w)) ;
			
			menu = textf_popupB->textf_popupB ;
		}

		call_data->menuToPost = menu ;

		if (call_data->menuToPost != (Widget) 0) {
			call_data->postIt = True ;
		}

		XtFree(selection) ;
	}
}
