/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STDFM_RPC_H_RPCGEN
#define	_STDFM_RPC_H_RPCGEN

#include <rpc/rpc.h>

typedef int IntT;

typedef u_int UIntT;

typedef char *StringT;

typedef int ErrorT;

typedef int BoolT;

struct FmRpcNiceErrorT {
	ErrorT code;
	StringT message;
};
typedef struct FmRpcNiceErrorT FmRpcNiceErrorT;

typedef struct {
	u_int FmRpcCommandsT_len;
	IntT *FmRpcCommandsT_val;
} FmRpcCommandsT;

struct FmRpcCommandsArgT {
	UIntT doc;
	FmRpcCommandsT commands;
};
typedef struct FmRpcCommandsArgT FmRpcCommandsArgT;

struct FmRpcNewDocArgT {
	StringT template;
};
typedef struct FmRpcNewDocArgT FmRpcNewDocArgT;

struct FmRpcNewDocReturnT {
	UIntT doc;
	FmRpcNiceErrorT nice;
};
typedef struct FmRpcNewDocReturnT FmRpcNewDocReturnT;

struct FmRpcOpenDocArgT {
	StringT doc;
};
typedef struct FmRpcOpenDocArgT FmRpcOpenDocArgT;

struct FmRpcOpenDocReturnT {
	UIntT doc;
	FmRpcNiceErrorT nice;
};
typedef struct FmRpcOpenDocReturnT FmRpcOpenDocReturnT;

struct FmRpcImportArgT {
	BoolT isCurrentDoc;
	UIntT doc;
	StringT file;
	BoolT isCopy;
};
typedef struct FmRpcImportArgT FmRpcImportArgT;

struct FmRpcSaveDocArgT {
	UIntT doc;
	StringT file;
	IntT mode;
	BoolT isMakeBackup;
	IntT saveOptions;
};
typedef struct FmRpcSaveDocArgT FmRpcSaveDocArgT;

struct FmRpcSaveTextArgT {
	UIntT doc;
	StringT file;
	IntT mode;
	BoolT isMakeBackup;
	IntT saveOptions;
};
typedef struct FmRpcSaveTextArgT FmRpcSaveTextArgT;

struct FmRpcSaveMifArgT {
	UIntT doc;
	StringT file;
	IntT mode;
	BoolT isMakeBackup;
	IntT saveOptions;
};
typedef struct FmRpcSaveMifArgT FmRpcSaveMifArgT;

struct FmRpcGoToLinkArgT {
	UIntT doc;
	StringT dstDoc;
	StringT tag;
	BoolT isNewWindow;
};
typedef struct FmRpcGoToLinkArgT FmRpcGoToLinkArgT;

struct FmRpcMessageArgT {
	StringT doc;
	StringT message;
};
typedef struct FmRpcMessageArgT FmRpcMessageArgT;

struct FmRpcListExternalsArgT {
	UIntT doc;
	StringT file;
};
typedef struct FmRpcListExternalsArgT FmRpcListExternalsArgT;

struct FmRpcEditInsetArgT {
	StringT insetFile;
	BoolT isIntern;
};
typedef struct FmRpcEditInsetArgT FmRpcEditInsetArgT;

struct FmRpcUpdateInsetArgT {
	StringT insetFile;
};
typedef struct FmRpcUpdateInsetArgT FmRpcUpdateInsetArgT;

#define	FM_RPC_PROG	300009
#define	FM_RPC_VERS	1
#define	FM_RPC_COMMANDS	1
extern  FmRpcNiceErrorT * fm_rpc_commands_1();
#define	FM_RPC_NEW_DOC	100
extern  FmRpcNewDocReturnT * fm_rpc_new_doc_1();
#define	FM_RPC_OPEN_DOC	101
extern  FmRpcOpenDocReturnT * fm_rpc_open_doc_1();
#define	FM_RPC_IMPORT	102
extern  FmRpcNiceErrorT * fm_rpc_import_1();
#define	FM_RPC_SAVE_DOC	103
extern  FmRpcNiceErrorT * fm_rpc_save_doc_1();
#define	FM_RPC_SAVE_TEXT	104
extern  FmRpcNiceErrorT * fm_rpc_save_text_1();
#define	FM_RPC_SAVE_MIF	105
extern  FmRpcNiceErrorT * fm_rpc_save_mif_1();
#define	FM_RPC_LIST_EXTERNALS	106
extern  FmRpcNiceErrorT * fm_rpc_list_externals_1();
#define	FM_RPC_QUIT_APP	107
extern  FmRpcNiceErrorT * fm_rpc_quit_app_1();
#define	FM_RPC_GO_TO_LINK	202
extern  FmRpcNiceErrorT * fm_rpc_go_to_link_1();
#define	FM_RPC_MESSAGE	203
extern  FmRpcNiceErrorT * fm_rpc_message_1();
#define	FM_RPC_LAUNCH	300
extern  FmRpcNiceErrorT * fm_rpc_launch_1();
#define	FM_RPC_EDIT_INSET	301
extern  FmRpcNiceErrorT * fm_rpc_edit_inset_1();
#define	FM_RPC_UPDATE_INSET	302
extern  FmRpcNiceErrorT * fm_rpc_update_inset_1();
extern int fm_rpc_prog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_IntT();
extern bool_t xdr_UIntT();
extern bool_t xdr_StringT();
extern bool_t xdr_ErrorT();
extern bool_t xdr_BoolT();
extern bool_t xdr_FmRpcNiceErrorT();
extern bool_t xdr_FmRpcCommandsT();
extern bool_t xdr_FmRpcCommandsArgT();
extern bool_t xdr_FmRpcNewDocArgT();
extern bool_t xdr_FmRpcNewDocReturnT();
extern bool_t xdr_FmRpcOpenDocArgT();
extern bool_t xdr_FmRpcOpenDocReturnT();
extern bool_t xdr_FmRpcImportArgT();
extern bool_t xdr_FmRpcSaveDocArgT();
extern bool_t xdr_FmRpcSaveTextArgT();
extern bool_t xdr_FmRpcSaveMifArgT();
extern bool_t xdr_FmRpcGoToLinkArgT();
extern bool_t xdr_FmRpcMessageArgT();
extern bool_t xdr_FmRpcListExternalsArgT();
extern bool_t xdr_FmRpcEditInsetArgT();
extern bool_t xdr_FmRpcUpdateInsetArgT();

#endif /* !_STDFM_RPC_H_RPCGEN */
