/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stdfm_rpc.h"

bool_t
xdr_IntT(xdrs, objp)
	register XDR *xdrs;
	IntT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_UIntT(xdrs, objp)
	register XDR *xdrs;
	UIntT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_u_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_StringT(xdrs, objp)
	register XDR *xdrs;
	StringT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ErrorT(xdrs, objp)
	register XDR *xdrs;
	ErrorT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_BoolT(xdrs, objp)
	register XDR *xdrs;
	BoolT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcNiceErrorT(xdrs, objp)
	register XDR *xdrs;
	FmRpcNiceErrorT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_ErrorT(xdrs, &objp->code))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->message))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcCommandsT(xdrs, objp)
	register XDR *xdrs;
	FmRpcCommandsT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_array(xdrs, (char **)&objp->FmRpcCommandsT_val, (u_int *) &objp->FmRpcCommandsT_len, 150,
		sizeof (IntT), (xdrproc_t) xdr_IntT))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcCommandsArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcCommandsArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_FmRpcCommandsT(xdrs, &objp->commands))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcNewDocArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcNewDocArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_StringT(xdrs, &objp->template))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcNewDocReturnT(xdrs, objp)
	register XDR *xdrs;
	FmRpcNewDocReturnT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_FmRpcNiceErrorT(xdrs, &objp->nice))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcOpenDocArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcOpenDocArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_StringT(xdrs, &objp->doc))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcOpenDocReturnT(xdrs, objp)
	register XDR *xdrs;
	FmRpcOpenDocReturnT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_FmRpcNiceErrorT(xdrs, &objp->nice))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcImportArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcImportArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_BoolT(xdrs, &objp->isCurrentDoc))
		return (FALSE);
	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_BoolT(xdrs, &objp->isCopy))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcSaveDocArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcSaveDocArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_IntT(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_BoolT(xdrs, &objp->isMakeBackup))
		return (FALSE);
	if (!xdr_IntT(xdrs, &objp->saveOptions))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcSaveTextArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcSaveTextArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_IntT(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_BoolT(xdrs, &objp->isMakeBackup))
		return (FALSE);
	if (!xdr_IntT(xdrs, &objp->saveOptions))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcSaveMifArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcSaveMifArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->file))
		return (FALSE);
	if (!xdr_IntT(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_BoolT(xdrs, &objp->isMakeBackup))
		return (FALSE);
	if (!xdr_IntT(xdrs, &objp->saveOptions))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcGoToLinkArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcGoToLinkArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->dstDoc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->tag))
		return (FALSE);
	if (!xdr_BoolT(xdrs, &objp->isNewWindow))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcMessageArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcMessageArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_StringT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->message))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcListExternalsArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcListExternalsArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_UIntT(xdrs, &objp->doc))
		return (FALSE);
	if (!xdr_StringT(xdrs, &objp->file))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcEditInsetArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcEditInsetArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_StringT(xdrs, &objp->insetFile))
		return (FALSE);
	if (!xdr_BoolT(xdrs, &objp->isIntern))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_FmRpcUpdateInsetArgT(xdrs, objp)
	register XDR *xdrs;
	FmRpcUpdateInsetArgT *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_StringT(xdrs, &objp->insetFile))
		return (FALSE);
	return (TRUE);
}
