/* XPM */

static char *aboutHelpPixmap_icon [] = { 
"100 100 3 1",
"  c #000084 m black",
". s buttonBackground c #dededededede m white",
"o c #9ca69ca8ffff m white",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"..............................................oooooooooo............................................",
".........................................ooooo           ...........................................",
"........................................oo                 .........................................",
"......................................ooo                   ........................................",
".....................................oo                       ......................................",
"....................................oo                         .....................................",
"...................................oo                           ....................................",
"...................................o                             ...................................",
"...................................o                             ...................................",
"..................................o             ......            ..................................",
".................................oo          ...........           .................................",
".................................o          .............          .................................",
".................................o         ...............          ................................",
".................................o         ...............o         ................................",
".................................o        ................o         ................................",
".................................o        ................o         ................................",
".................................o        ................o         ................................",
".................................o        ................o         ................................",
".................................o        ...............oo         ................................",
".................................o        ..............oo         .................................",
".................................o        .............oo          .................................",
"..................................        ............oo          ..................................",
"...................................      ............oo           ..................................",
"...................................................ooo           ...................................",
"..................................................oo            ....................................",
".................................................oo            .....................................",
"................................................oo            ......................................",
"...............................................oo            .......................................",
"..............................................oo            ........................................",
"..............................................o            .........................................",
".............................................oo          ...........................................",
".............................................o          ............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
".............................................o         .............................................",
"..............................................         .............................................",
"...............................................       ..............................................",
"....................................................................................................",
"................................................ooo.................................................",
"..............................................ooo   ................................................",
"..............................................o       ..............................................",
".............................................oo       ..............................................",
".............................................o         .............................................",
".............................................o         .............................................",
"..............................................         .............................................",
"...............................................       ..............................................",
"...............................................       ..............................................",
".................................................   ................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"....................................................................................................",
"...................................................................................................."
};

static char *upArrowIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGrey m black",
". c LightGrey m white",
"b s buttonBackground c #dededededede m white",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbb  bbbbbbbbbbb",
"bbbbbbbbbb .. bbbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbb ...... bbbbbbbb",
"bbbbbbb ........ bbbbbbb",
"bbbbbb .......... bbbbbb",
"bbbbb     ....     bbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb      bbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb"
};

static char *rightArrowIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGrey m black",
". c LightGrey m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"ooooooooooooo oooooooooo",
"ooooooooooooo  ooooooooo",
"ooooooooooooo . oooooooo",
"ooooooooooooo .. ooooooo",
"ooooo         ... oooooo",
"ooooo ............ ooooo",
"ooooo ............. oooo",
"ooooo ............. oooo",
"ooooo ............ ooooo",
"ooooo         ... oooooo",
"ooooooooooooo .. ooooooo",
"ooooooooooooo . oooooooo",
"ooooooooooooo  ooooooooo",
"ooooooooooooo oooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *leftArrowIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGrey m black",
". c LightGrey m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooo ooooooooooooo",
"ooooooooo  ooooooooooooo",
"oooooooo . ooooooooooooo",
"ooooooo .. ooooooooooooo",
"oooooo ...         ooooo",
"ooooo ............ ooooo",
"oooo ............. ooooo",
"oooo ............. ooooo",
"ooooo ............ ooooo",
"oooooo ...         ooooo",
"ooooooo .. ooooooooooooo",
"oooooooo . ooooooooooooo",
"ooooooooo  ooooooooooooo",
"oooooooooo ooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *editPasteIPixmap_icon [] = { 
"24 24 4 1",
"  c SlateGrey m black",
". c SlateGrey m black",
"o c LightGrey m white",
"O s buttonBackground c #dededededede m white",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOO    OOOOOOOOOO",
"OOOOOO     oo     OOOOOO",
"OOOOO ooo o  o ooo OOOOO",
"OOOOO oo oooooo oo OOOOO",
"OOOOO oo        oo OOOOO",
"OOOOO oooooooooooo OOOOO",
"OOOOO ooooo....... OOOOO",
"OOOOO ooooo.ooooo..OOOOO",
"OOOOO ooooo.ooooo.o.OOOO",
"OOOOO ooooo.o...o...OOOO",
"OOOOO ooooo.ooooooo.OOOO",
"OOOOO ooooo.o.....o.OOOO",
"OOOOOO     .ooooooo.OOOO",
"OOOOOOOOOOO.........OOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO"
};

static char *editCutIPixmap_icon [] = { 
"24 24 2 1",
"  c SlateGrey m black",
". s buttonBackground c #dededededede m white",
"........................",
"........................",
"........................",
"........................",
"........................",
"........................",
".......... ... .........",
".......... ... .........",
".......... ... .........",
"..........  .  .........",
"........... . ..........",
"...........   ..........",
"............ ...........",
"...........   ..........",
"........... .   ........",
".........   . .. .......",
"........ .. . .. .......",
"........ .. . .. .......",
"........ .. ..  ........",
".........  .............",
"........................",
"........................",
"........................",
"........................"
};

static char *editCopyIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGrey m black",
". c LightGrey m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"ooooo      ooooooooooooo",
"ooooo ....  oooooooooooo",
"ooooo .... . ooooooooooo",
"ooooo .  .       ooooooo",
"ooooo ..... ....  oooooo",
"ooooo .     .... . ooooo",
"ooooo ..... .  .    oooo",
"ooooo .     ....... oooo",
"ooooo ..... .     . oooo",
"ooooo       ....... oooo",
"ooooooooooo .     . oooo",
"ooooooooooo ....... oooo",
"ooooooooooo         oooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *fileOpenIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGray m black",
". c LightGrey m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooo   ooooooo",
"ooooooooooooo ooo o oooo",
"oooooooooooooooooo  oooo",
"oooooo   oooooooo   oooo",
"ooooo ...       oooooooo",
"ooooo ......... oooooooo",
"ooooo ......... oooooooo",
"ooooo ....          oooo",
"ooooo ... ......... oooo",
"ooooo .. ......... ooooo",
"ooooo . ......... oooooo",
"ooooo  ......... ooooooo",
"ooooo           oooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *fileNewIPixmap_icon [] = { 
"24 24 3 1",
"  s buttonBackground c #dededededede m white",
". c SlateGray m black",
"o c LightGrey m white",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"      .......           ",
"      .ooooo..          ",
"      .ooooo.o.         ",
"      .ooooo.oo.        ",
"      .ooooo.ooo.       ",
"      .ooooo......      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      ............      ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "
};

static char *fileOpenPixmap_icon [] = { 
"24 24 4 1",
"  c #000000 m black",
". c tan m white",
"o c DarkGoldenrod m white",
"O s buttonBackground c #dededededede m white",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOO   OOOOOOO",
"OOOOOOOOOOOOO OOO O OOOO",
"OOOOOOOOOOOOOOOOOO  OOOO",
"OOOOOO   OOOOOOOO   OOOO",
"OOOOO ooo       OOOOOOOO",
"OOOOO ooooooooo OOOOOOOO",
"OOOOO ooooooooo OOOOOOOO",
"OOOOO oooo          OOOO",
"OOOOO ooo ......... OOOO",
"OOOOO oo ......... OOOOO",
"OOOOO o ......... OOOOOO",
"OOOOO  ......... OOOOOOO",
"OOOOO           OOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO"
};

static char *editCopyPixmap_icon [] = { 
"24 24 3 1",
"  c #000000 m black",
". c #FFFFFF m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"ooooo      ooooooooooooo",
"ooooo ....  oooooooooooo",
"ooooo .... . ooooooooooo",
"ooooo .  .       ooooooo",
"ooooo ..... ....  oooooo",
"ooooo .     .... . ooooo",
"ooooo ..... .  .    oooo",
"ooooo .     ....... oooo",
"ooooo ..... .     . oooo",
"ooooo       ....... oooo",
"ooooooooooo .     . oooo",
"ooooooooooo ....... oooo",
"ooooooooooo         oooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *editCutPixmap_icon [] = { 
"24 24 2 1",
"  c Black m black",
". s buttonBackground c #dededededede m white",
"........................",
"........................",
"........................",
"........................",
"........................",
".......... ... .........",
".......... ... .........",
".......... ... .........",
"..........  .  .........",
"........... . ..........",
"...........   ..........",
"............ ...........",
"...........   ..........",
"........... .   ........",
".........   . .. .......",
"........ .. . .. .......",
"........ .. . .. .......",
"........ .. ..  ........",
".........  .............",
"........................",
"........................",
"........................",
"........................",
"........................"
};

static char *fileNewPixmap_icon [] = { 
"24 24 4 1",
"  s buttonBackground c #dededededede m white",
". c Black m black",
"o c White m white",
"O c LightGrey m white",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"      .......           ",
"      .ooooo..          ",
"      .ooooo.O.         ",
"      .ooooo.OO.        ",
"      .ooooo.OOO.       ",
"      .ooooo......      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      .oooooooooo.      ",
"      ............      ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "
};

static char *editPastePixmap_icon [] = { 
"24 24 6 1",
"  c #000000 m black",
". c DimGrey m black",
"o c tan m white",
"O c #FFFFFF m white",
"a c #FFFF00 m white",
"b s buttonBackground c #dededededede m white",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbb    bbbbbbbbbb",
"bbbbbb     aa     bbbbbb",
"bbbbb ooo a  a ooo bbbbb",
"bbbbb oo aaaaaa oo bbbbb",
"bbbbb oo        oo bbbbb",
"bbbbb oooooooooooo bbbbb",
"bbbbb ooooo....... bbbbb",
"bbbbb ooooo.OOOOO..bbbbb",
"bbbbb ooooo.OOOOO.O.bbbb",
"bbbbb ooooo.O...O...bbbb",
"bbbbb ooooo.OOOOOOO.bbbb",
"bbbbb ooooo.O.....O.bbbb",
"bbbbbb     .OOOOOOO.bbbb",
"bbbbbbbbbbb.........bbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb"
};

static char *helpHelpPixmap_icon [] = { 
"24 24 2 1",
"  c #000084 m black",
". s buttonBackground c #dededededede m white",
"........................",
"........................",
"........................",
"........................",
"........................",
"..........    ..........",
".........      .........",
"........  ...   ........",
"........  ....  ........",
"........  ...   ........",
"............   .........",
"...........   ..........",
"...........  ...........",
"...........  ...........",
"...........  ...........",
"........................",
"...........  ...........",
"...........  ...........",
"........................",
"........................",
"........................",
"........................",
"........................",
"........................"
};

static char *helpHelpIPixmap_icon [] = { 
"24 24 2 1",
"  c SlateGrey m black",
". s buttonBackground c #dededededede m white",
"........................",
"........................",
"........................",
"........................",
"........................",
"..........    ..........",
".........      .........",
"........  ...   ........",
"........  ....  ........",
"........  ...   ........",
"............   .........",
"...........   ..........",
"...........  ...........",
"...........  ...........",
"...........  ...........",
"........................",
"...........  ...........",
"...........  ...........",
"........................",
"........................",
"........................",
"........................",
"........................",
"........................"
};

static char *fileSavePixmap_icon [] = { 
"24 24 4 1",
"  c #000000 m black",
". c white m white",
"o c MistyRose m white",
"d s buttonBackground c #dededededede m white",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"ddddd              ddddd",
"ddddd o ........ o ddddd",
"ddddd o ........ o ddddd",
"ddddd o ........ o ddddd",
"ddddd o ........ o ddddd",
"ddddd o ........ o ddddd",
"ddddd o ........ o ddddd",
"ddddd oo        oo ddddd",
"ddddd oooooooooooo ddddd",
"ddddd oo         o ddddd",
"ddddd oo      .. o ddddd",
"ddddd oo      .. o ddddd",
"ddddd oo      .. o ddddd",
"dddddd             ddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd"
};

static char *fileSaveIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGray m black",
". c LightGrey m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"ooooo              ooooo",
"ooooo . ........ . ooooo",
"ooooo . ........ . ooooo",
"ooooo . ........ . ooooo",
"ooooo . ........ . ooooo",
"ooooo . ........ . ooooo",
"ooooo . ........ . ooooo",
"ooooo ..        .. ooooo",
"ooooo ............ ooooo",
"ooooo ..         . ooooo",
"ooooo ..      .. . ooooo",
"ooooo ..      .. . ooooo",
"ooooo ..      .. . ooooo",
"oooooo             ooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *filePrintPixmap_icon [] = { 
"24 24 4 1",
"  c #000000 m black",
". c white m white",
"O c #848284 m white",
"d s buttonBackground c #dededededede m white",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddd        dddddddd",
"dddddddd ...... dddddddd",
"dddddddd .   .. dddddddd",
"dddddddd ...... dddddddd",
"dddddddd .    . dddddddd",
"dddddddd ...... dddddddd",
"ddddddd          ddddddd",
"dddddd .......... dddddd",
"ddddd  OOOOOOOOOO  ddddd",
"ddddd ............ ddddd",
"ddddd . .......... ddddd",
"ddddd ............ ddddd",
"dddddd            dddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd"
};

static char *filePrintIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGrey m black",
". c LightGrey m white",
"d s buttonBackground c #dededededede m white",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddd        dddddddd",
"dddddddd ...... dddddddd",
"dddddddd .   .. dddddddd",
"dddddddd ...... dddddddd",
"dddddddd .    . dddddddd",
"dddddddd ...... dddddddd",
"ddddddd          ddddddd",
"dddddd .......... dddddd",
"ddddd              ddddd",
"ddddd ............ ddddd",
"ddddd . .......... ddddd",
"ddddd ............ ddddd",
"dddddd            dddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd",
"dddddddddddddddddddddddd"
};

static char *rightArrowPixmap_icon [] = { 
"24 24 3 1",
"  c #000000 m black",
". c #6666cfcfffff m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"ooooooooooooo oooooooooo",
"ooooooooooooo  ooooooooo",
"ooooooooooooo . oooooooo",
"ooooooooooooo .. ooooooo",
"ooooo         ... oooooo",
"ooooo ............ ooooo",
"ooooo ............. oooo",
"ooooo ............. oooo",
"ooooo ............ ooooo",
"ooooo         ... oooooo",
"ooooooooooooo .. ooooooo",
"ooooooooooooo . oooooooo",
"ooooooooooooo  ooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *leftArrowPixmap_icon [] = { 
"24 24 3 1",
"  c #000000 m black",
". c #6666cfcfffff m white",
"o s buttonBackground c #dededededede m white",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooo ooooooooooooo",
"ooooooooo  ooooooooooooo",
"oooooooo . ooooooooooooo",
"ooooooo .. ooooooooooooo",
"oooooo ...         ooooo",
"ooooo ............ ooooo",
"oooo ............. ooooo",
"oooo ............. ooooo",
"ooooo ............ ooooo",
"oooooo ...         ooooo",
"ooooooo .. ooooooooooooo",
"oooooooo . ooooooooooooo",
"ooooooooo  ooooooooooooo",
"oooooooooo ooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo",
"oooooooooooooooooooooooo"
};

static char *upArrowPixmap_icon [] = { 
"24 24 3 1",
"  c #000000 m black",
". c #6666cfcfffff m white",
"b s buttonBackground c #dededededede m white",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbb  bbbbbbbbbbb",
"bbbbbbbbbb .. bbbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbb ...... bbbbbbbb",
"bbbbbbb ........ bbbbbbb",
"bbbbbb .......... bbbbbb",
"bbbbb     ....     bbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb .... bbbbbbbbb",
"bbbbbbbbb      bbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb",
"bbbbbbbbbbbbbbbbbbbbbbbb"
};

static char *helpShellPixmap_icon [] = { 
"48 48 2 1",
"  c DodgerBlue m white",
". c #FF0000 m black",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                      ........                  ",
"                   .............                ",
"                 ................               ",
"                ..................              ",
"                ..................              ",
"                ......      .......             ",
"               .....         ......             ",
"               .....          .....             ",
"               ....           .....             ",
"                ...           ....              ",
"                             .....              ",
"                            ......              ",
"                          .......               ",
"                        ........                ",
"                      .........                 ",
"                     .........                  ",
"                    ........                    ",
"                    .......                     ",
"                    .....                       ",
"                    ....                        ",
"                     ..                         ",
"                                                ",
"                                                ",
"                   ....                         ",
"                  ......                        ",
"                 .......                        ",
"                 .......                        ",
"                 .......                        ",
"                 ......                         ",
"                  ....                          ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
};

static char *helpShellMask_icon [] = { 
"48 48 2 1",
"  c DodgerBlue m white",
". c #FF0000 m black",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                      ........                  ",
"                   .............                ",
"                 ................               ",
"                ..................              ",
"                ..................              ",
"                ......      .......             ",
"               .....         ......             ",
"               .....          .....             ",
"               ....           .....             ",
"                ...           ....              ",
"                             .....              ",
"                            ......              ",
"                          .......               ",
"                        ........                ",
"                      .........                 ",
"                     .........                  ",
"                    ........                    ",
"                    .......                     ",
"                    .....                       ",
"                    ....                        ",
"                     ..                         ",
"                                                ",
"                                                ",
"                   ....                         ",
"                  ......                        ",
"                 .......                        ",
"                 .......                        ",
"                 .......                        ",
"                 ......                         ",
"                  ....                          ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "
};

static char *homePixmap_icon [] = { 
"24 24 4 1",
"  c #000000 m black",
". c tan m white",
"o c #FFFFFF m white",
"a s buttonBackground c #dededededede m white",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaa aaaaaaaaaaaa",
"aaaaaa   a . aaaaaaaaaaa",
"aaaaaa .  ... aaaaaaaaaa",
"aaaaaa . .. .. aaaaaaaaa",
"aaaaaa ... . .. aaaaaaaa",
"aaaaaa .. ... .. aaaaaaa",
"aaaaa .. ..... .. aaaaaa",
"aaaa    .......    aaaaa",
"aaaaaa ......... aaaaaaa",
"aaaaaa ...   ... aaaaaaa",
"aaaaaa ... o ... aaaaaaa",
"aaaaaa ... o ... aaaaaaa",
"aaaaaa ... o ... aaaaaaa",
"aaaaaa           aaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa"
};

static char *homeIPixmap_icon [] = { 
"24 24 3 1",
"  c SlateGrey m black",
". c LightGrey m white",
"O s buttonBackground c #dededededede m white",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOO OOOOOOOOOOOO",
"OOOOOO   O . OOOOOOOOOOO",
"OOOOOO .  ... OOOOOOOOOO",
"OOOOOO . .. .. OOOOOOOOO",
"OOOOOO ... . .. OOOOOOOO",
"OOOOOO .. ... .. OOOOOOO",
"OOOOO .. ..... .. OOOOOO",
"OOOO    .......    OOOOO",
"OOOOOO ......... OOOOOOO",
"OOOOOO ...   ... OOOOOOO",
"OOOOOO ... . ... OOOOOOO",
"OOOOOO ... . ... OOOOOOO",
"OOOOOO ... . ... OOOOOOO",
"OOOOOO           OOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO",
"OOOOOOOOOOOOOOOOOOOOOOOO"
};

