
# Explicit setting of SHELL - beware since this gets inherited
# by commands invoked by Make

SHELL=/bin/sh
TARGET=generic
ABIDIR=
SYSDIR=
ABICFLAGS=
ABICCFLAGS=
ABILDFLAGS=

# Default rule
all: all-${TARGET}

##: system Solaris 32bit Ansi C/C++
##: default cpp
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr/dt
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR} -R${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/openwin/include -I/usr/openwin/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/openwin/lib${SYSDIR} -R/usr/openwin/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXmu -lXt -lX11 -lXext -lSM -lICE -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS} -lce -ltt -ldl -liostream
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#ABI2CFLAGS=
#ABI2CCFLAGS=-compat=5 -features=no%conststrings
#ABI2LDFLAGS=
#ABI2ABIDIR=/ansi32
#ABI2SYSDIR=
#ABICFLAGS=${ABI2CFLAGS}
#ABICCFLAGS=${ABI2CCFLAGS}
#ABILDFLAGS=${ABI2LDFLAGS}
#SYSDIR=
#ABIDIR=/ansi32
##: end

##: system Solaris 64bit Ansi C/C++ (sparc)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr/dt
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR} -R${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/openwin/include -I/usr/openwin/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/openwin/lib${SYSDIR} -R/usr/openwin/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXmu -lXt -lX11 -lXext -lSM -lICE -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS} -lce -ltt -ldl -liostream
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#ABI2-64CFLAGS=-xarch=v9
#ABI2-64CCFLAGS=-xarch=v9 -compat=5
#ABI2-64LDFLAGS=
#ABI2-64ABIDIR=/sparcv9
#ABI2-64SYSDIR=/sparcv9
#ABICFLAGS=${ABI2-64CFLAGS}
#ABICCFLAGS=${ABI2-64CCFLAGS}
#ABILDFLAGS=${ABI2-64LDFLAGS}
#SYSDIR=/sparcv9
#ABIDIR=/sparcv9
##: end

##: system Solaris 32bit Workshop4 Compatible C++
##: default c
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr/dt
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR} -R${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/openwin/include -I/usr/openwin/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/openwin/lib${SYSDIR} -R/usr/openwin/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXmu -lXt -lX11 -lXext -lSM -lICE -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS} -lce -ltt -ldl -liostream
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#ABI1CFLAGS=
#ABI1CCFLAGS=-compat=4
#ABI1LDFLAGS=
#ABI1ABIDIR=/compat-pre5
#ABI1SYSDIR=
#ABICFLAGS=${ABI1CFLAGS}
#ABICCFLAGS=${ABI1CCFLAGS}
#ABILDFLAGS=${ABI1LDFLAGS}
#SYSDIR=
#ABIDIR=/compat-pre5
##: end

##: system Solaris 64bit AMD C/C++ (opteron)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr/dt
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR} -R${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/openwin/include -I/usr/openwin/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/openwin/lib${SYSDIR} -R/usr/openwin/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXmu -lXt -lX11 -lXext -lSM -lICE -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS} -lce -ltt -ldl -liostream
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#AMD-64CFLAGS=-xarch=amd64
#AMD-64CCFLAGS=-xarch=amd64 -compat=5
#AMD-64LDFLAGS=
#AMD-64ABIDIR=/amd64
#AMD-64SYSDIR=/amd64
#ABICFLAGS=${AMD-64CFLAGS}
#ABICCFLAGS=${AMD-64CCFLAGS}
#ABILDFLAGS=${AMD-64LDFLAGS}
#SYSDIR=/amd64
#ABIDIR=/amd64
##: end

##: system Solaris 32/64 Multi-target C/C++
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr/dt
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR} -R${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/openwin/include -I/usr/openwin/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/openwin/lib${SYSDIR} -R/usr/openwin/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXmu -lXt -lX11 -lXext -lSM -lICE -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS} -lce -ltt -ldl -liostream
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
## Extra ABI targets for solaris2_abi_multiabi
#ABI1CFLAGS=
#ABI1CCFLAGS=-compat=4
#ABI1LDFLAGS=
#ABI1ABIDIR=/compat-pre5
#ABI1SYSDIR=
#
#all-compat-pre5::
#	make -f Makefile TARGET=generic ABICFLAGS="${ABI1CFLAGS}" ABICCFLAGS="${ABI1CCFLAGS}" ABILDFLAGS="${ABI1LDFLAGS}" ABIDIR="/${ABI1ABIDIR}" SYSDIR="${ABI1SYSDIR}" all
#
#server-compat-pre5::
#	make -f Makefile TARGET=generic ABICFLAGS="${ABI1CFLAGS}" ABICCFLAGS="${ABI1CCFLAGS}" ABILDFLAGS="${ABI1LDFLAGS}" ABIDIR="/${ABI1ABIDIR}" SYSDIR="${ABI1SYSDIR}" server
#
#ABI2CFLAGS=
#ABI2CCFLAGS=-compat=5 -features=no%conststrings
#ABI2LDFLAGS=
#ABI2ABIDIR=/ansi32
#ABI2SYSDIR=
#
#all-ansi32::
#	make -f Makefile TARGET=generic ABICFLAGS="${ABI2CFLAGS}" ABICCFLAGS="${ABI2CCFLAGS}" ABILDFLAGS="${ABI2LDFLAGS}" ABIDIR="/${ABI2ABIDIR}" SYSDIR="${ABI2SYSDIR}" all
#
#server-ansi32::
#	make -f Makefile TARGET=generic ABICFLAGS="${ABI2CFLAGS}" ABICCFLAGS="${ABI2CCFLAGS}" ABILDFLAGS="${ABI2LDFLAGS}" ABIDIR="/${ABI2ABIDIR}" SYSDIR="${ABI2SYSDIR}" server
#
#ABI2-64CFLAGS=-xarch=v9
#ABI2-64CCFLAGS=-xarch=v9 -compat=5
#ABI2-64LDFLAGS=
#ABI2-64ABIDIR=/sparcv9
#ABI2-64SYSDIR=/sparcv9
#
#all-sparcv9::
#	make -f Makefile TARGET=generic ABICFLAGS="${ABI2-64CFLAGS}" ABICCFLAGS="${ABI2-64CCFLAGS}" ABILDFLAGS="${ABI2-64LDFLAGS}" ABIDIR="/${ABI2-64ABIDIR}" SYSDIR="${ABI2-64SYSDIR}" all
#
#server-sparcv9::
#	make -f Makefile TARGET=generic ABICFLAGS="${ABI2-64CFLAGS}" ABICCFLAGS="${ABI2-64CCFLAGS}" ABILDFLAGS="${ABI2-64LDFLAGS}" ABIDIR="/${ABI2-64ABIDIR}" SYSDIR="${ABI2-64SYSDIR}" server
#
#compatCFLAGS=
#compatCCFLAGS=
#compatLDFLAGS=
#compatABIDIR=/pre5
#compatSYSDIR=
#
#all-pre5::
#	make -f Makefile TARGET=generic ABICFLAGS="${compatCFLAGS}" ABICCFLAGS="${compatCCFLAGS}" ABILDFLAGS="${compatLDFLAGS}" ABIDIR="/${compatABIDIR}" SYSDIR="${compatSYSDIR}" all
#
#server-pre5::
#	make -f Makefile TARGET=generic ABICFLAGS="${compatCFLAGS}" ABICCFLAGS="${compatCCFLAGS}" ABILDFLAGS="${compatLDFLAGS}" ABIDIR="/${compatABIDIR}" SYSDIR="${compatSYSDIR}" server
#
#AMD-64CFLAGS=-xarch=amd64
#AMD-64CCFLAGS=-xarch=amd64 -compat=5
#AMD-64LDFLAGS=
#AMD-64ABIDIR=/amd64
#AMD-64SYSDIR=/amd64
#
#all-amd64::
#	make -f Makefile TARGET=generic ABICFLAGS="${AMD-64CFLAGS}" ABICCFLAGS="${AMD-64CCFLAGS}" ABILDFLAGS="${AMD-64LDFLAGS}" ABIDIR="/${AMD-64ABIDIR}" SYSDIR="${AMD-64SYSDIR}" all
#
#server-amd64::
#	make -f Makefile TARGET=generic ABICFLAGS="${AMD-64CFLAGS}" ABICCFLAGS="${AMD-64CCFLAGS}" ABILDFLAGS="${AMD-64LDFLAGS}" ABIDIR="/${AMD-64ABIDIR}" SYSDIR="${AMD-64SYSDIR}" server
#
##: end

##: system HP-UX 11.x
## -Wp,-H900000 recommended if too many cpp defines.
## For K&R code generation use:
## CPPFLAGS=-Wp,-H900000
## For ANSI C code generation use:
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=-I/usr/include/Motif2.1
#MOTIF_LIB_DIR=/usr/lib/Motif2.1
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11R6 -I/usr/include/X11R6/X11
#XLIBS=-L/usr/lib/X11R6 -L/usr/lib/Motif2.1
#X11_LIB_DIR=/usr/lib/X11R6
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11 -lXp
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L/usr/lib/Motif2.1 -lXm -L/usr/lib/X11R6 -lXext
##: end

##: system HP-UX 10.x
## -Wp,-H900000 recommended if too many cpp defines.
## For K&R code generation use:
## CPPFLAGS=-Wp,-H900000
## For ANSI C code generation use:
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=-I/usr/include/Motif1.2
#MOTIF_LIB_DIR=/usr/lib/Motif1.2_R6
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11R6 -I/usr/include/X11R6/X11
#XLIBS=-L/usr/lib/X11R6 -L/usr/lib/Motif2.1
#X11_LIB_DIR=/usr/lib/X11R6
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11 -lXp
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L/usr/lib/Motif2.1 -lXm -L/usr/lib/X11R6 -lXext
##: end

##: system HP-UX 9.x
## -Wp,-H900000 recommended if too many cpp defines.
## For K&R code generation use:
## CPPFLAGS=-Wp,-H900000
## For ANSI C code generation use:
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=-I/usr/include/Motif2.1
#MOTIF_LIB_DIR=/usr/lib/Motif2.1
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11R6
#XLIBS=-L/usr/lib/X11R6 -L/usr/lib/Motif2.1
#X11_LIB_DIR=/usr/lib/X11R6
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11 -lXp
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L/usr/lib/Motif2.1 -lXm -L${X11_LIB_DIR} -lXext
##: end

##: system IBM Aix
# No User Defined Widgets configured
#CCC=xlC -+
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-lXm -lXext -lXmu
##: end

##: system Compaq "Digital Unix"
# No User Defined Widgets configured
#CCC=cxx -msg_quiet
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/shlib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=-L/usr/shlib
#X11_LIB_DIR=/usr/shlib
#XSYSLIBS=-lXt -lX11 -lXp -ldnet_stub
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-lXm -lXext -lXmu
##: end

##: system Concurrent (MAXION System 5 Release 4)
# No User Defined Widgets configured
#CCC=/opt/epc/bin/c++ -D__epc
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-lXt -lX11 -lXp -lnsl -lsocket -lgen -lresolv
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-lXm -lXext -lXmu
##: end

##: system NCR (System 5 Release 4)
# No User Defined Widgets configured
#CCC=cc -Hcppext=C,cxx
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-lXt -lX11 -lXp -lnsl -lsocket -lgen -lresolv
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-lXm -lXext -lXmu
##: end

##: system NEC (System 5 Release 4)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-lXt -lX11 -lXp -lnsl -lsocket -lgen -lresolv
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-lXm -lXext -lXmu
##: end

##: system SCO UnixWare 7 (was Novell)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/X/include -I/usr/X/include/X11
#XLIBS=-L/usr/lib -L/usr/ccs/lib
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lSM -lICE -lX11 -lXp -lnsl -lsocket -lgen -lresolv
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-lXm
##: end

##: system HAL Solaris 2.x
## For ANSI C code generation use:
## CPPFLAGS=-KV7 -Xa
# No User Defined Widgets configured
#CCC=hcc -KV7
#MOTIFHOME=/usr/dt
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=/usr/dt/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/openwin/include -I/usr/openwin/include/X11
#XLIBS=-L/usr/dt/lib -R/usr/dt/lib -L/usr/openwin/lib -R/usr/openwin/lib
#X11_LIB_DIR=/usr/openwin/lib
#XSYSLIBS=-L/usr/openwin/lib -lXt -lX11 -lXp -lce -ltt -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS} -ldl
#MOTIFLIB=-L/usr/dt/lib @UWEXTRALIBS@ -lXm -lXext -lXmu
##: end

##: system Silicon Graphics (new 32 bit)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#n32CFLAGS=-n32
#n32CCFLAGS=-n32
#n32LDFLAGS=-n32
#n32ABIDIR=/n32
#n32SYSDIR=32
#ABICFLAGS=${n32CFLAGS}
#ABICCFLAGS=${n32CCFLAGS}
#ABILDFLAGS=${n32LDFLAGS}
#SYSDIR=32
#ABIDIR=/n32
##: end

##: system Silicon Graphics (new 64 bit)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#n64CFLAGS=-64
#n64CCFLAGS=-64
#n64LDFLAGS=-64
#n64ABIDIR=/n64
#n64SYSDIR=64
#ABICFLAGS=${n64CFLAGS}
#ABICCFLAGS=${n64CCFLAGS}
#ABILDFLAGS=${n64LDFLAGS}
#SYSDIR=64
#ABIDIR=/n64
##: end

##: system Silicon Graphics (old 32 bit)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#o32CFLAGS=-o32
#o32CCFLAGS=-o32
#o32LDFLAGS=-o32
#o32ABIDIR=/o32
#o32SYSDIR=
#ABICFLAGS=${o32CFLAGS}
#ABICCFLAGS=${o32CCFLAGS}
#ABILDFLAGS=${o32LDFLAGS}
#SYSDIR=
#ABIDIR=/o32
##: end

##: system Silicon Graphics (Irix 6.5 Defaults)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#dfltCFLAGS=-n32
#dfltCCFLAGS=-n32
#dfltLDFLAGS=-n32
#dfltABIDIR=/n32
#dfltSYSDIR=32
#ABICFLAGS=${dfltCFLAGS}
#ABICCFLAGS=${dfltCCFLAGS}
#ABILDFLAGS=${dfltLDFLAGS}
#SYSDIR=32
#ABIDIR=/n32
##: end

##: system Silicon Graphics (Pre 6.5 Defaults)
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
#tradCFLAGS=-o32
#tradCCFLAGS=-o32
#tradLDFLAGS=-o32
#tradABIDIR=/o32
#tradSYSDIR=
#ABICFLAGS=${tradCFLAGS}
#ABICCFLAGS=${tradCCFLAGS}
#ABILDFLAGS=${tradLDFLAGS}
#SYSDIR=
#ABIDIR=/o32
##: end

##: system Silicon Graphics 32/64 Multi-target C/C++
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=/usr
#MOTIFINCLUDES=-I${MOTIFHOME}/include
#MOTIF_LIB_DIR=${MOTIFHOME}/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib${SYSDIR}
#XSYSLIBS=-L${X11_LIB_DIR} -lXt -lX11
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L${MOTIF_LIB_DIR} -lXm
## Extra ABI targets for sg_irix_abi_multiabi
#o32CFLAGS=-o32
#o32CCFLAGS=-o32
#o32LDFLAGS=-o32
#o32ABIDIR=/o32
#o32SYSDIR=
#
#all-o32::
#	make -f Makefile TARGET=generic ABICFLAGS="${o32CFLAGS}" ABICCFLAGS="${o32CCFLAGS}" ABILDFLAGS="${o32LDFLAGS}" ABIDIR="/${o32ABIDIR}" SYSDIR="${o32SYSDIR}" all
#
#server-o32::
#	make -f Makefile TARGET=generic ABICFLAGS="${o32CFLAGS}" ABICCFLAGS="${o32CCFLAGS}" ABILDFLAGS="${o32LDFLAGS}" ABIDIR="/${o32ABIDIR}" SYSDIR="${o32SYSDIR}" server
#
#n32CFLAGS=-n32
#n32CCFLAGS=-n32
#n32LDFLAGS=-n32
#n32ABIDIR=/n32
#n32SYSDIR=32
#
#all-n32::
#	make -f Makefile TARGET=generic ABICFLAGS="${n32CFLAGS}" ABICCFLAGS="${n32CCFLAGS}" ABILDFLAGS="${n32LDFLAGS}" ABIDIR="/${n32ABIDIR}" SYSDIR="${n32SYSDIR}" all
#
#server-n32::
#	make -f Makefile TARGET=generic ABICFLAGS="${n32CFLAGS}" ABICCFLAGS="${n32CCFLAGS}" ABILDFLAGS="${n32LDFLAGS}" ABIDIR="/${n32ABIDIR}" SYSDIR="${n32SYSDIR}" server
#
#n64CFLAGS=-64
#n64CCFLAGS=-64
#n64LDFLAGS=-64
#n64ABIDIR=/n64
#n64SYSDIR=64
#
#all-n64::
#	make -f Makefile TARGET=generic ABICFLAGS="${n64CFLAGS}" ABICCFLAGS="${n64CCFLAGS}" ABILDFLAGS="${n64LDFLAGS}" ABIDIR="/${n64ABIDIR}" SYSDIR="${n64SYSDIR}" all
#
#server-n64::
#	make -f Makefile TARGET=generic ABICFLAGS="${n64CFLAGS}" ABICCFLAGS="${n64CCFLAGS}" ABILDFLAGS="${n64LDFLAGS}" ABIDIR="/${n64ABIDIR}" SYSDIR="${n64SYSDIR}" server
#
##: end

##: system SCO OpenServer 5
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-Bdynamic -L/usr/lib -lXt -lX11 -lXp -lsocket -lintl -lm
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-Bdynamic -lXm -lXext -lXmu
##: end

##: system QNX
# No User Defined Widgets configured
#CCC=CC
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib/X11
#XINCLUDES=${MOTIFINCLUDES} 	-I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib/X11
#XSYSLIBS=-N 128k -L/usr/lib/X11 -lXt_s -lX11_s -lXp_s -lXqnx_s -lXext -lsocket
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L/usr/lib/X11 -lXm -lXmu
##: end

##: system Lynx Real-Time OS (PPC)
# No User Defined Widgets configured
#CCC=g++
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-lXt -lX11 -lXext -lXp -lSM -lICE -lrpc -lnetinet
#UWXSYSLIBS=${XDROOT}/lib/xds/libnoxds.a ${XSYSLIBS}
#MOTIFLIB=-lXm -lXpm
##: end

##: system Linux (x86 64 bit)
# No User Defined Widgets configured
#CCC=g++
#MOTIFHOME=/usr/OpenMotif-2.1.31
#MOTIFINCLUDES=-I$(MOTIFHOME)/include
#MOTIF_LIB_DIR=$(MOTIFHOME)/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/X11R6/include -I/usr/X11R6/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/X11R6/lib${SYSDIR}
#XSYSLIBS=-L$(X11_LIB_DIR) -lXt -lX11 -lXext -lXp
#UWXSYSLIBS=${XSYSLIBS} -ldl
#MOTIFLIB=-L$(MOTIFHOME)/lib${SYSDIR} -lXm -L/usr/X11R6/lib${SYSDIR} -lXext -lXmu
#X86_64CFLAGS=-m64
#X86_64CCFLAGS=-m64
#X86_64LDFLAGS=
#X86_64ABIDIR=/lib64
#X86_64SYSDIR=64
#ABICFLAGS=${X86_64CFLAGS}
#ABICCFLAGS=${X86_64CCFLAGS}
#ABILDFLAGS=${X86_64LDFLAGS}
#SYSDIR=64
#ABIDIR=/lib64
##: end

##: system Linux (x86)
# No User Defined Widgets configured
#CCC=g++
#MOTIFHOME=/usr/OpenMotif-2.1.31
#MOTIFINCLUDES=-I$(MOTIFHOME)/include
#MOTIF_LIB_DIR=$(MOTIFHOME)/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/X11R6/include -I/usr/X11R6/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/X11R6/lib${SYSDIR}
#XSYSLIBS=-L$(X11_LIB_DIR) -lXt -lX11 -lXext -lXp
#UWXSYSLIBS=${XSYSLIBS} -ldl
#MOTIFLIB=-L$(MOTIFHOME)/lib${SYSDIR} -lXm -L/usr/X11R6/lib${SYSDIR} -lXext -lXmu
#X86CFLAGS=-m32
#X86CCFLAGS=-m32
#X86LDFLAGS=
#X86ABIDIR=/lib32
#X86SYSDIR=
#ABICFLAGS=${X86CFLAGS}
#ABICCFLAGS=${X86CCFLAGS}
#ABILDFLAGS=${X86LDFLAGS}
#SYSDIR=
#ABIDIR=/lib32
##: end

##: system Linux 32/64 Multi-target C/C++
# No User Defined Widgets configured
#CCC=g++
#MOTIFHOME=/usr/OpenMotif-2.1.31
#MOTIFINCLUDES=-I$(MOTIFHOME)/include
#MOTIF_LIB_DIR=$(MOTIFHOME)/lib${SYSDIR}
#XINCLUDES=${MOTIFINCLUDES} -I/usr/X11R6/include -I/usr/X11R6/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/X11R6/lib${SYSDIR}
#XSYSLIBS=-L$(X11_LIB_DIR) -lXt -lX11 -lXext -lXp
#UWXSYSLIBS=${XSYSLIBS} -ldl
#MOTIFLIB=-L$(MOTIFHOME)/lib${SYSDIR} -lXm -L/usr/X11R6/lib${SYSDIR} -lXext -lXmu
## Extra ABI targets for linux_abi_multiabi
#X86CFLAGS=-m32
#X86CCFLAGS=-m32
#X86LDFLAGS=
#X86ABIDIR=/lib32
#X86SYSDIR=
#
#all-lib32::
#	make -f Makefile TARGET=generic ABICFLAGS="${X86CFLAGS}" ABICCFLAGS="${X86CCFLAGS}" ABILDFLAGS="${X86LDFLAGS}" ABIDIR="/${X86ABIDIR}" SYSDIR="${X86SYSDIR}" all
#
#server-lib32::
#	make -f Makefile TARGET=generic ABICFLAGS="${X86CFLAGS}" ABICCFLAGS="${X86CCFLAGS}" ABILDFLAGS="${X86LDFLAGS}" ABIDIR="/${X86ABIDIR}" SYSDIR="${X86SYSDIR}" server
#
#X86_64CFLAGS=-m64
#X86_64CCFLAGS=-m64
#X86_64LDFLAGS=
#X86_64ABIDIR=/lib64
#X86_64SYSDIR=64
#
#all-lib64::
#	make -f Makefile TARGET=generic ABICFLAGS="${X86_64CFLAGS}" ABICCFLAGS="${X86_64CCFLAGS}" ABILDFLAGS="${X86_64LDFLAGS}" ABIDIR="/${X86_64ABIDIR}" SYSDIR="${X86_64SYSDIR}" all
#
#server-lib64::
#	make -f Makefile TARGET=generic ABICFLAGS="${X86_64CFLAGS}" ABICCFLAGS="${X86_64CCFLAGS}" ABILDFLAGS="${X86_64LDFLAGS}" ABIDIR="/${X86_64ABIDIR}" SYSDIR="${X86_64SYSDIR}" server
#
##: end

##: system Concurrent Night Hawk (PowerUX3.1)
# No User Defined Widgets configured
#CCC=c++
#MOTIFHOME=
#MOTIFINCLUDES=
#MOTIF_LIB_DIR=/usr/lib
#XINCLUDES=${MOTIFINCLUDES} -I/usr/include/X11
#XLIBS=
#X11_LIB_DIR=/usr/lib
#XSYSLIBS=-L/usr/lib -Bdynamic -lXt -lX11 -lXp -lnsl -lsocket -lgen
#UWXSYSLIBS=${XSYSLIBS}
#MOTIFLIB=-L/usr/lib -lXm -Bdynamic -lXext -lXmu
##: end


XPMDIR = ${XDROOT}/src/xpm/lib
XPMLIBDIR = ${XDROOT}/user_widgets/obj
LDFLAGS = ${XLIBS} -L${XPMLIBDIR}
XPMLIB = -lXpm

XDCLASS = $(XDROOT)/src/xdclass
XDCLASSLIBS = $(XDCLASS)/lib/libxdclass.a
TOOLTIPS = ${XDROOT}/src/tooltips
TOOLTIPSLIB = ${XDROOT}/src/tooltips/lib/libtooltips.a

CFLAGS=-I. -I../libgen -I../client ${XINCLUDES} -I$(TOOLTIPS)/h -I${XDCLASS}/h -I${XPMDIR}
CCFLAGS=${CFLAGS} -I${XDCLASS}/h

SOURCES=\
	help.cxx\
	CGuru.cxx\
	CJStop.cxx\
	CTopic.cxx\
	CHistList.cxx\
	CHTMLParser.cxx\
	GuruStubs.cxx

OBJECTS=\
	help.o\
	CGuru.o\
	CJStop.o\
	CTopic.o\
	CHistList.o\
	CHTMLParser.o\
	GuruStubs.o

LIBS=\
	../libgen/lib.a ../client/lib.a

all-generic: CHECKENV xdhelp

xdhelp: $(OBJECTS) $(LIBS)
	$(CCC) $(LDFLAGS) $(OBJECTS) $(LIBS) $(XDCLASSLIBS) ${TOOLTIPSLIB} $(XPMLIB) $(MOTIFLIB) $(UWXSYSLIBS) -o $@

depend:
	makedepend -- $(CFLAGS) $(CPPFLAGS) -- $(SOURCES)
	makedepend -a -- $(CCFLAGS) $(CPPFLAGS) -- $(SOURCES)

clean:
	rm -f $(OBJECTS) xdhelp

CHECKENV:
	@test -n "$(XDROOT)" || (echo You must set \$$XDROOT in the makefile or in your shell environment; exit 1)

help.o: help.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c help.cxx

CGuru.o: CGuru.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c CGuru.cxx

GuruStubs.o: GuruStubs.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c GuruStubs.cxx

CJStop.o: CJStop.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c CJStop.cxx

CTopic.o: CTopic.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c CTopic.cxx

CHistList.o: CHistList.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c CHistList.cxx

CHTMLParser.o: CHTMLParser.cxx
	$(CCC) $(CCFLAGS) $(CPPFLAGS) -c CHTMLParser.cxx

# DO NOT DELETE THIS LINE -- make depend depends on it.

