xdhelp.title: XD/Help
xdhelp*mainForm.dialogTitle: XD/Help
xdhelp*fileCB.labelString: File
xdhelp*fileNewItem.labelString: New
xdhelp*fileNewItem.acceleratorText: Ctrl+N
xdhelp*fileOpenItem.labelString: Open...
xdhelp*fileOpenItem.acceleratorText: Ctrl+O
xdhelp*fileCloseItem.labelString: Close
xdhelp*fileSaveItem.labelString: Save
xdhelp*fileSaveItem.acceleratorText: Ctrl+S
xdhelp*fileSaveAsItem.labelString: Save As...
xdhelp*fileRevertItem.labelString: Revert to Saved
xdhelp*filePrintItem.labelString: Print...
xdhelp*filePrintItem.acceleratorText: Ctrl+P
xdhelp*fileQuitItem.labelString: Exit
xdhelp*fileQuitItem.acceleratorText: Ctrl+E
xdhelp*editCB.labelString: Edit
xdhelp*editUndoItem.labelString: Undo
xdhelp*editUndoItem.acceleratorText: Ctrl+Z
xdhelp*editCutItem.labelString: Cut
xdhelp*editCutItem.acceleratorText: Ctrl+X
xdhelp*editCopyItem.labelString: Copy
xdhelp*editCopyItem.acceleratorText: Ctrl+C
xdhelp*editPasteItem.labelString: Paste
xdhelp*editPasteItem.acceleratorText: Ctrl+V
xdhelp*editClearItem.labelString: Clear
xdhelp*editClearItem.acceleratorText: Del
xdhelp*navCB.labelString: Navigation
xdhelp*navBackItem.labelString: Back
xdhelp*navBackItem.acceleratorText: Ctrl+B
xdhelp*navForwardItem.labelString: Forward
xdhelp*navForwardItem.acceleratorText: Ctrl+F
xdhelp*navIndexItem.labelString: Index
xdhelp*navHistoryItem.labelString: History...
xdhelp*navFindItem.labelString: Find...
xdhelp*helpCB.labelString: Help
xdhelp*helpOnVersionItem.labelString: On Version...
xdhelp*helpIndexItem.labelString: Help...
xdhelp*statusLabel.labelString: 
xdhelp*newButton.labelString: <>
xdhelp*openButton.labelString: <>
xdhelp*saveButton.labelString: <>
xdhelp*printButton.labelString: <>
xdhelp*cutButton.labelString: <>
xdhelp*copyButton.labelString: <>
xdhelp*pasteButton.labelString: <>
xdhelp*backButton.labelString: <>
xdhelp*forwardButton.labelString: <>
xdhelp*firstButton.labelString: <>
xdhelp*helpButton.labelString: Help
xdhelp*linksLabel.labelString: Links
xdhelp*aboutDT.dialogTitle: About XD/Help
xdhelp*aboutOKButton.labelString: OK
xdhelp*prognameText.labelString: XD/Help
xdhelp*aboutText.labelString: Copyright (c) 1990-2007 Imperial Software Technology Ltd. All Rights Reserved.\nCopyright (c) 1995-2007 Sun Microsystems, Inc. All Rights Reserved.\nVersion 7.9 2007/04/10
xdhelp*printDT.dialogTitle: Print
xdhelp*okButton.labelString: Print
xdhelp*cancelButton.labelString: Cancel
xdhelp*helpButton.labelString: Help
xdhelp*printLabel.labelString: Print command:
xdhelp*openFileFSB.dialogTitle: Open File
xdhelp*cantOpenMB.dialogTitle: Error
xdhelp*cantOpenMB.messageString: I can't find the help database.\nPlease tell me where it is.
xdhelp*sysErrorMB.dialogTitle: Error
xdhelp*sysErrorMB.messageString: Error: 
xdhelp*noItemsFoundMB.dialogTitle: Find...
xdhelp*noItemsFoundMB.messageString: No matching items were found.
xdhelp*findDT.dialogTitle: Find Text
xdhelp*findButton.labelString: Find
xdhelp*closeButton.labelString: Close
xdhelp*helpButton.labelString: Help
xdhelp*saveFileFSB.dialogTitle: Save File
xdhelp*historyForm.dialogTitle: History
xdhelp*gotoButton.labelString: Go to
xdhelp*closeButton.labelString: Close
xdhelp*helpButton.labelString: Help
! Generated by X-Designer

xdhelp.buttonBackground: #dededededede

! helpShell

! mainForm

! menuBar

! fileCB
xdhelp*fileCB.mnemonic: F

! fileMenu

! fileNewItem
xdhelp*fileNewItem.mnemonic: N
xdhelp*fileNewItem.accelerator: Ctrl<Key>N

! fileOpenItem
xdhelp*fileOpenItem.mnemonic: O
xdhelp*fileOpenItem.accelerator: Ctrl<Key>O

! fileCloseItem
xdhelp*fileCloseItem.mnemonic: C

! fileSaveItem
xdhelp*fileSaveItem.mnemonic: S
xdhelp*fileSaveItem.accelerator: Ctrl<Key>S

! fileSaveAsItem
xdhelp*fileSaveAsItem.mnemonic: A

! fileRevertItem
xdhelp*fileRevertItem.mnemonic: R

! filePrintItem
xdhelp*filePrintItem.mnemonic: P
xdhelp*filePrintItem.accelerator: Ctrl<Key>P

! fileQuitItem
xdhelp*fileQuitItem.mnemonic: E
xdhelp*fileQuitItem.accelerator: Ctrl<Key>E

! editCB
xdhelp*editCB.mnemonic: E

! editMenu

! editUndoItem
xdhelp*editUndoItem.mnemonic: Z
xdhelp*editUndoItem.accelerator: Ctrl<Key>Z

! editCutItem
xdhelp*editCutItem.mnemonic: t
xdhelp*editCutItem.accelerator: Ctrl<Key>X

! editCopyItem
xdhelp*editCopyItem.mnemonic: C
xdhelp*editCopyItem.accelerator: Ctrl<Key>C

! editPasteItem
xdhelp*editPasteItem.mnemonic: P
xdhelp*editPasteItem.accelerator: Ctrl<Key>V

! editClearItem
xdhelp*editClearItem.mnemonic: e
xdhelp*editClearItem.accelerator: <Key>osfDelete

! navCB
xdhelp*navCB.mnemonic: N

! navMenu

! navBackItem
xdhelp*navBackItem.mnemonic: B
xdhelp*navBackItem.accelerator: Ctrl<Key>B

! navForwardItem
xdhelp*navForwardItem.mnemonic: F
xdhelp*navForwardItem.accelerator: Ctrl<Key>F

! navIndexItem
xdhelp*navIndexItem.mnemonic: I

! navHistoryItem
xdhelp*navHistoryItem.mnemonic: H

! navFindItem
xdhelp*navFindItem.mnemonic: d

! helpCB
xdhelp*helpCB.mnemonic: H

! helpMenu

! helpOnVersionItem
xdhelp*helpOnVersionItem.mnemonic: O

! helpIndexItem
xdhelp*helpIndexItem.mnemonic: H

! statusBar

! statusLabel

! toolBar

! newButton
xdhelp*newButton.tooltip: Opens a new (empty) help document

! openButton
xdhelp*openButton.tooltip: Opens a help document

! saveButton
xdhelp*saveButton.tooltip: Saves the current help document

! printButton
xdhelp*printButton.tooltip: Prints the current help document

! separator14

! cutButton
xdhelp*cutButton.tooltip: Cuts the current document to the clipboard

! copyButton
xdhelp*copyButton.tooltip: Copies the current document to the clipboard

! pasteButton
xdhelp*pasteButton.tooltip: Pastes a document from the clipboard

! separator15

! backButton
xdhelp*backButton.tooltip: Reverts to the previous help document

! forwardButton
xdhelp*forwardButton.tooltip: Moves to the next help document

! firstButton
xdhelp*firstButton.tooltip: Moves to the first help document

! separator16

! tb_helpButton
xdhelp*helpButton.tooltip: Provides help on XD/Help

! panedWindow

! form5

! helpText

! titleText

! linksList

! linksLabel


! aboutShell

! aboutDT

! aboutOKButton

! rowcol2

! prognameText
xdhelp*prognameText.foreground: red
xdhelp*prognameText.fontList: -adobe-helvetica-bold-o-normal--24-240-75-75-p-138-iso8859-1

! xhd_picture

! aboutText


! printDialog

! printDT

! printOKbutton

! button34

! button36

! printForm

! printLabel

! printCommand
xdhelp*printCommand.value: lpr


! openFileDialog

! openFileFSB


! cantOpenShell

! cantOpenMB


! sysErrAlert

! sysErrorMB

! messageLabel


! findAlert

! noItemsFoundMB


! findDialog

! findDT

! findButton

! closeButton

! helpButton

! findText


! saveFileDialog

! saveFileFSB


! historyShell

! historyForm

! historyList

! gotoButton

! button72

! button74

