! Generated by X-Designer


! calc_shell
MCalc.title: MCalc

! calc_form

! digits_rc

! digit7
MCalc*digit7.labelString: 7

! digit4
MCalc*digit4.labelString: 4

! digit1
MCalc*digit1.labelString: 1

! dec_point
MCalc*dec_point.labelString: .

! digit8
MCalc*digit8.labelString: 8

! digit5
MCalc*digit5.labelString: 5

! digit2
MCalc*digit2.labelString: 2

! digit0
MCalc*digit0.labelString: 0

! digit9
MCalc*digit9.labelString: 9

! digit6
MCalc*digit6.labelString: 6

! digit3
MCalc*digit3.labelString: 3

! eq_b
MCalc*eq_b.labelString: =

! add_b
MCalc*add_b.labelString: +

! sub_b
MCalc*sub_b.labelString: -

! mul_b
MCalc*mul_b.labelString: *

! div_b
MCalc*div_b.labelString: /

! calc_display

! unary_rc

! sgn_b
MCalc*sgn_b.labelString: +/-

! m_b
MCalc*m_b.labelString: M

! ac_b
MCalc*ac_b.labelString: AC

! mplus_b
MCalc*mplus_b.labelString: M+

! ce_b
MCalc*ce_b.labelString: C

! mminus_b
MCalc*mminus_b.labelString: M-

! logo_l

