! Generated by X-Designer


! calc_shell
MCalc.title: MCalc

! calc_form

! digits_rc

! digit7
MCalc*digit7.labelString: 7

! digit4
MCalc*digit4.labelString: 4

! digit1
MCalc*digit1.labelString: 1

! dec_point
MCalc*dec_point.labelString: .

! digit8
MCalc*digit8.labelString: 8

! digit5
MCalc*digit5.labelString: 5

! digit2
MCalc*digit2.labelString: 2

! digit0
MCalc*digit0.labelString: 0

! digit9
MCalc*digit9.labelString: 9

! digit6
MCalc*digit6.labelString: 6

! digit3
MCalc*digit3.labelString: 3

! eq_b
MCalc*eq_b.labelString: =

! add_b
MCalc*add_b.labelString: +

! sub_b
MCalc*sub_b.labelString: -

! mul_b
MCalc*mul_b.labelString: *

! div_b
MCalc*div_b.labelString: /

! calc_display

! unary_rc

! sin_b
MCalc*sin_b.labelString: sin

! cos_b
MCalc*cos_b.labelString: cos

! tan_b
MCalc*tan_b.labelString: tan

! log_b
MCalc*log_b.labelString: log

! ln_b
MCalc*ln_b.labelString: ln

! m_b
MCalc*m_b.labelString: M

! sqr_b
MCalc*sqr_b.labelString: sqr

! pow_b
MCalc*pow_b.labelString: x^y

! exp_b
MCalc*exp_b.labelString: e^x

! rec_b
MCalc*rec_b.labelString: 1/x

! fact_b
MCalc*fact_b.labelString: x!

! mplus_b
MCalc*mplus_b.labelString: M+

! and_b
MCalc*and_b.labelString: And

! or_b
MCalc*or_b.labelString: Or

! xor_b
MCalc*xor_b.labelString: Xor

! lsh_b
MCalc*lsh_b.labelString: <<

! rsh_b
MCalc*rsh_b.labelString: >>

! mminus_b
MCalc*mminus_b.labelString: M-

! ac_b
MCalc*ac_b.labelString: AC

! ce_b
MCalc*ce_b.labelString: C

! sgn_b
MCalc*sgn_b.labelString: +/-

! bra_b
MCalc*bra_b.labelString: (

! ket_b
MCalc*ket_b.labelString: )

! inv_b
MCalc*inv_b.labelString: Inv

! optionMenu1
MCalc*optionMenu1.labelString: 

! label1

! drg_cb

! deg_b
MCalc*deg_b.labelString: Deg

! rad_b
MCalc*rad_b.labelString: Rad

! gra_b
MCalc*gra_b.labelString: Gra

