# Copyright 2002,2003 Sun Microsystems, Inc. All Rights Reserved
# 
# Makefile for Cdlib
#

CFLAGS=-g -xsb
CCFLAGS=-g -sb

Cdlib:

clean:
	@-$(RM) -rf .sb Cdlib \
	  *.BAK *.delta core .prof .nm mon.out \
	  *.tcov *.d tags *~ SunWS_cache

