/*
** Generated by X-Designer
*/
#ifndef _textf_base_h
#define _textf_base_h

#define XD_MOTIF


typedef struct textf_popupA_s {
	Widget textf_popupA;
	Widget cut_b;
	Widget copy_b;
	Widget paste_b;
} textf_popupA_t, *textf_popupA_p;

typedef struct textf_popupB_s {
	Widget textf_popupB;
	Widget read_b;
	Widget write_b;
} textf_popupB_t, *textf_popupB_p;

typedef struct textf_base_s {
	Widget textf_base;
	textf_popupA_p textf_popupA;
	textf_popupB_p textf_popupB;
} textf_base_t, *textf_base_p;


extern Widget shell;
extern textf_base_p textf_base;
extern textf_popupA_p textf_popupA;
extern textf_popupB_p textf_popupB;

extern textf_popupA_p create_textf_popupA (Widget);
extern void delete_textf_popupA ( textf_popupA_p );
extern textf_popupB_p create_textf_popupB (Widget);
extern void delete_textf_popupB ( textf_popupB_p );
extern textf_base_p create_textf_base (Widget);
extern void delete_textf_base ( textf_base_p );
extern void create_shell (Display *, char *, int, char **);



#endif
