/*
** Generated by X-Designer
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <stdlib.h>
#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/TextF.h>


#include "textf_base.h"

extern void popup_handler_callback(Widget, XtPointer, XtPointer) ;
Widget shell = (Widget) NULL;
textf_base_p textf_base = (textf_base_p) NULL;
textf_popupA_p textf_popupA = (textf_popupA_p) NULL;
textf_popupB_p textf_popupB = (textf_popupB_p) NULL;



textf_popupA_p create_textf_popupA (Widget parent)
{
	Widget children[3];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	textf_popupA_p textf_popupA = (textf_popupA_p)NULL;

	textf_popupA = (textf_popupA_p) XtMalloc (  sizeof ( textf_popupA_t ) );
	XtSetArg(al[ac], XmNpopupEnabled, XmPOPUP_AUTOMATIC); ac++;
	XtSetArg(al[ac], XmNmenuPost, "<Button3>"); ac++;
	textf_popupA->textf_popupA = XmCreatePopupMenu ( parent, (char *) "textf_popupA", al, ac );
	ac = 0;
	xmstrings[0] = XmStringGenerate ( "Cut", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	textf_popupA->cut_b = XmCreatePushButton ( textf_popupA->textf_popupA, (char *) "cut_b", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( "Copy", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	textf_popupA->copy_b = XmCreatePushButton ( textf_popupA->textf_popupA, (char *) "copy_b", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( "Paste", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	textf_popupA->paste_b = XmCreatePushButton ( textf_popupA->textf_popupA, (char *) "paste_b", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if ((children[ac] = textf_popupA->cut_b) != (Widget) 0) { ac++; }
	if ((children[ac] = textf_popupA->copy_b) != (Widget) 0) { ac++; }
	if ((children[ac] = textf_popupA->paste_b) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	return textf_popupA;
}

void delete_textf_popupA ( textf_popupA_p textf_popupA )
{
	if ( ! textf_popupA )
		return;
	XtFree ( ( char * )textf_popupA );
}

textf_popupB_p create_textf_popupB (Widget parent)
{
	Widget children[2];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	textf_popupB_p textf_popupB = (textf_popupB_p)NULL;

	textf_popupB = (textf_popupB_p) XtMalloc (  sizeof ( textf_popupB_t ) );
	XtSetArg(al[ac], XmNpopupEnabled, XmPOPUP_AUTOMATIC); ac++;
	XtSetArg(al[ac], XmNmenuPost, "<Button3>"); ac++;
	textf_popupB->textf_popupB = XmCreatePopupMenu ( parent, (char *) "textf_popupB", al, ac );
	ac = 0;
	xmstrings[0] = XmStringGenerate ( "Read", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	textf_popupB->read_b = XmCreatePushButton ( textf_popupB->textf_popupB, (char *) "read_b", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringGenerate ( "Write", XmFONTLIST_DEFAULT_TAG, XmCHARSET_TEXT, NULL );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	textf_popupB->write_b = XmCreatePushButton ( textf_popupB->textf_popupB, (char *) "write_b", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	if ((children[ac] = textf_popupB->read_b) != (Widget) 0) { ac++; }
	if ((children[ac] = textf_popupB->write_b) != (Widget) 0) { ac++; }
	if (ac > 0) { XtManageChildren(children, ac); }
	ac = 0;
	return textf_popupB;
}

void delete_textf_popupB ( textf_popupB_p textf_popupB )
{
	if ( ! textf_popupB )
		return;
	XtFree ( ( char * )textf_popupB );
}

textf_base_p create_textf_base (Widget parent)
{
	Widget children[2];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	textf_base_p textf_base = (textf_base_p)NULL;

	textf_base = (textf_base_p) XtMalloc (  sizeof ( textf_base_t ) );
	textf_base->textf_base = XmCreateTextField ( parent, (char *) "textf_base", al, ac );
	textf_base->textf_popupA = create_textf_popupA ( textf_base->textf_base );
	textf_base->textf_popupB = create_textf_popupB ( textf_base->textf_base );
	if (textf_base->textf_base)
		XtAddCallback( textf_base->textf_base, XmNpopupHandlerCallback, popup_handler_callback, (XtPointer) 0 );
	return textf_base;
}

void delete_textf_base ( textf_base_p textf_base )
{
	if ( ! textf_base )
		return;
	delete_textf_popupA ( textf_base->textf_popupA );
	delete_textf_popupB ( textf_base->textf_popupB );
	XtFree ( ( char * )textf_base );
}

void create_shell (Display *display, char *app_name, int app_argc, char **app_argv)
{
	Widget children[1];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XtPointer tmp_value;             /* ditto */

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNargc, app_argc); ac++;
	XtSetArg(al[ac], XmNargv, app_argv); ac++;
	shell = XtAppCreateShell(app_name, (char *) "XApplication", sessionShellWidgetClass, display, al, ac);

	ac = 0;
	textf_base = create_textf_base ( shell );

	if (textf_base->textf_base != (Widget) 0) { XtManageChild ( textf_base->textf_base); }
}

